version: "3.8"

services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/traefik/data/traefik.yml:/traefik.yml:ro
      - /opt/traefik/data/acme.json:/acme.json
    networks:
      - traefik-public

  poste:
    image: analogic/poste.io:latest
    container_name: poste
    restart: unless-stopped
    hostname: mail.hubbr.org
    environment:
      - HTTPS=OFF
    volumes:
      - /opt/poste/data:/data
    networks:
      - traefik-public
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.poste.rule=Host(`mail.hubbr.org`)"
      - "traefik.http.routers.poste.entrypoints=websecure"
      - "traefik.http.routers.poste.tls.certresolver=letsencrypt"
      - "traefik.http.services.poste.loadbalancer.server.port=80"

networks:
  traefik-public:
    external: true
